### ISSUE TITLE
Hansokus are forced always on first point place (which is wrong)

### ISSUE THREAD

**Issue by dim-geo** [softwaremagico/KendoTournamentManager#629]
Imagine this scenario:

<img width="2433" height="190" alt="Image" src="https://github.com/user-attachments/assets/0ca1505d-e581-4f95-8886-81afcc50dbf2" />

and then test fighter get another hansoku.
Program cannot propagate point, it says "score value not added".
You have to clean the first point, then the hansoku point is added automatically to the first place which is wrong.

Ideally the program should do this automatically:
<img width="2433" height="190" alt="Image" src="https://github.com/user-attachments/assets/9339e55a-0e55-40f3-9edc-3f8b4432364c" />

**Comment by dim-geo** [comment]
Hi, now hansokus go straight into second point place which is wrong as well.
The code should check if first point is there and if a point is there then score hansoku in the second place, otherwise score hansoku in first place.
Should I raise this in a new ticket?

**Comment by softwaremagico** [comment]
Ok, from the previous fights, I can calculate your scores order preferences (if you want to go from the center to the competitors names or vice versa). But if the hansoku is done on the first fight, still will fail. 

The best I can propose now is to set a new property on the tournament to define the scoring positions.

**Comment by dim-geo** [comment]
Not all positions are equal!

if you score a point to outer boxes then it counts as if 2 points were scored.
If you score a point to inner box, then it counts as 1 point.

Check this:
<img width="2198" height="1014" alt="Image" src="https://github.com/user-attachments/assets/095cf594-0d54-4656-b08d-02d153fca85f" />

I would recommend to implement the 'hard' way and check which box is filled and fill the other box when a hansoku need to be filled.
If that's too much work, then leave it as it is and document it.
I don't think it's a good idea to define another tournament property for this.
Please correct the points calculated regardless of the position filled since this impact statistics/winners/losers.

**Comment by softwaremagico** [comment]
Ok, the ranking is fixed. Still I will check it later.

The hansokus can be set to the empty box left. The only problem is the first box when no other point is there. I cat get from other fights from the tournament, but still, if it is the first fight the solution will not be perfect.

**Comment by dim-geo** [comment]
Hi, Hansokus are now ok. They are added wherever there is free box.
However the score is still not ok... Both fighters below should have one point. John Doe is not the winner.

(I deleted the old tournament and created a new one just to make sure no garbage is left in DB)

<img width="2207" height="1016" alt="Image" src="https://github.com/user-attachments/assets/ec205a4a-efe1-43c6-8c22-a2af2b9aa6a3" />
